// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: internal/v1/services/rest_api/energyMeter.proto

package energyMeterApiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	energyMeter "https://github.com/victorcel/proto-enertbit-grpc-models/pkg/v1/energyMeter"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestEnergyMeter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"energy_meter" json:"energy_meter"
	EnergyMeter *energyMeter.EnergyMeters `protobuf:"bytes,1,opt,name=energy_meter,json=energyMeter,proto3" json:"energy_meter,omitempty"`
}

func (x *RequestEnergyMeter) Reset() {
	*x = RequestEnergyMeter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEnergyMeter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnergyMeter) ProtoMessage() {}

func (x *RequestEnergyMeter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnergyMeter.ProtoReflect.Descriptor instead.
func (*RequestEnergyMeter) Descriptor() ([]byte, []int) {
	return file_internal_v1_services_rest_api_energyMeter_proto_rawDescGZIP(), []int{0}
}

func (x *RequestEnergyMeter) GetEnergyMeter() *energyMeter.EnergyMeters {
	if x != nil {
		return x.EnergyMeter
	}
	return nil
}

type ResponseEnergyMeter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"energy_meter" json:"energy_meter"
	EnergyMeter *energyMeter.EnergyMeters `protobuf:"bytes,1,opt,name=energy_meter,json=energyMeter,proto3" json:"energy_meter,omitempty"`
}

func (x *ResponseEnergyMeter) Reset() {
	*x = ResponseEnergyMeter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEnergyMeter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEnergyMeter) ProtoMessage() {}

func (x *ResponseEnergyMeter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEnergyMeter.ProtoReflect.Descriptor instead.
func (*ResponseEnergyMeter) Descriptor() ([]byte, []int) {
	return file_internal_v1_services_rest_api_energyMeter_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseEnergyMeter) GetEnergyMeter() *energyMeter.EnergyMeters {
	if x != nil {
		return x.EnergyMeter
	}
	return nil
}

type ResponseGetEnergyMeters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"energy_meter" json:"energy_meter"
	EnergyMeter []*energyMeter.EnergyMeters `protobuf:"bytes,1,rep,name=energy_meter,json=energyMeter,proto3" json:"energy_meter,omitempty"`
}

func (x *ResponseGetEnergyMeters) Reset() {
	*x = ResponseGetEnergyMeters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetEnergyMeters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEnergyMeters) ProtoMessage() {}

func (x *ResponseGetEnergyMeters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEnergyMeters.ProtoReflect.Descriptor instead.
func (*ResponseGetEnergyMeters) Descriptor() ([]byte, []int) {
	return file_internal_v1_services_rest_api_energyMeter_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseGetEnergyMeters) GetEnergyMeter() []*energyMeter.EnergyMeters {
	if x != nil {
		return x.EnergyMeter
	}
	return nil
}

type RequestUpdateEnergyMeters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"id_request" json:"id_request"
	IdRequest *energyMeter.IdRequest `protobuf:"bytes,1,opt,name=id_request,json=idRequest,proto3" json:"id_request,omitempty"`
	// @inject_tag: bson:"energy_meter" json:"energy_meter"
	EnergyMeter *energyMeter.EnergyMeters `protobuf:"bytes,2,opt,name=energy_meter,json=energyMeter,proto3" json:"energy_meter,omitempty"`
}

func (x *RequestUpdateEnergyMeters) Reset() {
	*x = RequestUpdateEnergyMeters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUpdateEnergyMeters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateEnergyMeters) ProtoMessage() {}

func (x *RequestUpdateEnergyMeters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateEnergyMeters.ProtoReflect.Descriptor instead.
func (*RequestUpdateEnergyMeters) Descriptor() ([]byte, []int) {
	return file_internal_v1_services_rest_api_energyMeter_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUpdateEnergyMeters) GetIdRequest() *energyMeter.IdRequest {
	if x != nil {
		return x.IdRequest
	}
	return nil
}

func (x *RequestUpdateEnergyMeters) GetEnergyMeter() *energyMeter.EnergyMeters {
	if x != nil {
		return x.EnergyMeter
	}
	return nil
}

type DeleteEnergyMeters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"id_request" json:"id_request"
	IdRequest *energyMeter.IdRequest `protobuf:"bytes,1,opt,name=id_request,json=idRequest,proto3" json:"id_request,omitempty"`
}

func (x *DeleteEnergyMeters) Reset() {
	*x = DeleteEnergyMeters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEnergyMeters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnergyMeters) ProtoMessage() {}

func (x *DeleteEnergyMeters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnergyMeters.ProtoReflect.Descriptor instead.
func (*DeleteEnergyMeters) Descriptor() ([]byte, []int) {
	return file_internal_v1_services_rest_api_energyMeter_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEnergyMeters) GetIdRequest() *energyMeter.IdRequest {
	if x != nil {
		return x.IdRequest
	}
	return nil
}

var File_internal_v1_services_rest_api_energyMeter_proto protoreflect.FileDescriptor

var file_internal_v1_services_rest_api_energyMeter_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2f,
	0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d,
	0x65, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x29, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65,
	0x74, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0c, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0b, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x22, 0x5c, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0c, 0x65, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65,
	0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x0b, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72,
	0x22, 0x60, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x45, 0x0a, 0x0c, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0b, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x22, 0xa2, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x3e, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x09, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x45, 0x0a, 0x0c, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0b, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x3e, 0x0a,
	0x0a, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x09, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0xc3, 0x05,
	0x0a, 0x14, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x70, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x6f, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x2c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x6c, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65,
	0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x82, 0x01, 0x0a, 0x21, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x43, 0x75, 0x74, 0x4f, 0x72, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x4d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x7a, 0x0a, 0x1d, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x4d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65,
	0x74, 0x65, 0x72, 0x42, 0x72, 0x5a, 0x70, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x63, 0x74, 0x6f, 0x72,
	0x63, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x65, 0x6e, 0x65, 0x72, 0x74, 0x62,
	0x69, 0x74, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72,
	0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x65, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x3b, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74,
	0x65, 0x72, 0x41, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_v1_services_rest_api_energyMeter_proto_rawDescOnce sync.Once
	file_internal_v1_services_rest_api_energyMeter_proto_rawDescData = file_internal_v1_services_rest_api_energyMeter_proto_rawDesc
)

func file_internal_v1_services_rest_api_energyMeter_proto_rawDescGZIP() []byte {
	file_internal_v1_services_rest_api_energyMeter_proto_rawDescOnce.Do(func() {
		file_internal_v1_services_rest_api_energyMeter_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_v1_services_rest_api_energyMeter_proto_rawDescData)
	})
	return file_internal_v1_services_rest_api_energyMeter_proto_rawDescData
}

var file_internal_v1_services_rest_api_energyMeter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_v1_services_rest_api_energyMeter_proto_goTypes = []interface{}{
	(*RequestEnergyMeter)(nil),        // 0: proto.energyMeterApi.v1.RequestEnergyMeter
	(*ResponseEnergyMeter)(nil),       // 1: proto.energyMeterApi.v1.ResponseEnergyMeter
	(*ResponseGetEnergyMeters)(nil),   // 2: proto.energyMeterApi.v1.ResponseGetEnergyMeters
	(*RequestUpdateEnergyMeters)(nil), // 3: proto.energyMeterApi.v1.RequestUpdateEnergyMeters
	(*DeleteEnergyMeters)(nil),        // 4: proto.energyMeterApi.v1.DeleteEnergyMeters
	(*energyMeter.EnergyMeters)(nil),  // 5: proto.energyMeter.v1.EnergyMeters
	(*energyMeter.IdRequest)(nil),     // 6: proto.energyMeter.v1.IdRequest
	(*energyMeter.BoolResponse)(nil),  // 7: proto.energyMeter.v1.BoolResponse
}
var file_internal_v1_services_rest_api_energyMeter_proto_depIdxs = []int32{
	5,  // 0: proto.energyMeterApi.v1.RequestEnergyMeter.energy_meter:type_name -> proto.energyMeter.v1.EnergyMeters
	5,  // 1: proto.energyMeterApi.v1.ResponseEnergyMeter.energy_meter:type_name -> proto.energyMeter.v1.EnergyMeters
	5,  // 2: proto.energyMeterApi.v1.ResponseGetEnergyMeters.energy_meter:type_name -> proto.energyMeter.v1.EnergyMeters
	6,  // 3: proto.energyMeterApi.v1.RequestUpdateEnergyMeters.id_request:type_name -> proto.energyMeter.v1.IdRequest
	5,  // 4: proto.energyMeterApi.v1.RequestUpdateEnergyMeters.energy_meter:type_name -> proto.energyMeter.v1.EnergyMeters
	6,  // 5: proto.energyMeterApi.v1.DeleteEnergyMeters.id_request:type_name -> proto.energyMeter.v1.IdRequest
	0,  // 6: proto.energyMeterApi.v1.EnergyMetersServices.GetEnergyMeters:input_type -> proto.energyMeterApi.v1.RequestEnergyMeter
	0,  // 7: proto.energyMeterApi.v1.EnergyMetersServices.CreateEnergyMeters:input_type -> proto.energyMeterApi.v1.RequestEnergyMeter
	3,  // 8: proto.energyMeterApi.v1.EnergyMetersServices.UpdateEnergyMeters:input_type -> proto.energyMeterApi.v1.RequestUpdateEnergyMeters
	6,  // 9: proto.energyMeterApi.v1.EnergyMetersServices.DeleteEnergyMeters:input_type -> proto.energyMeter.v1.IdRequest
	0,  // 10: proto.energyMeterApi.v1.EnergyMetersServices.InstalledCutOrInactiveEnergyMeter:input_type -> proto.energyMeterApi.v1.RequestEnergyMeter
	0,  // 11: proto.energyMeterApi.v1.EnergyMetersServices.RecentInstallationEnergyMeter:input_type -> proto.energyMeterApi.v1.RequestEnergyMeter
	2,  // 12: proto.energyMeterApi.v1.EnergyMetersServices.GetEnergyMeters:output_type -> proto.energyMeterApi.v1.ResponseGetEnergyMeters
	1,  // 13: proto.energyMeterApi.v1.EnergyMetersServices.CreateEnergyMeters:output_type -> proto.energyMeterApi.v1.ResponseEnergyMeter
	7,  // 14: proto.energyMeterApi.v1.EnergyMetersServices.UpdateEnergyMeters:output_type -> proto.energyMeter.v1.BoolResponse
	7,  // 15: proto.energyMeterApi.v1.EnergyMetersServices.DeleteEnergyMeters:output_type -> proto.energyMeter.v1.BoolResponse
	2,  // 16: proto.energyMeterApi.v1.EnergyMetersServices.InstalledCutOrInactiveEnergyMeter:output_type -> proto.energyMeterApi.v1.ResponseGetEnergyMeters
	1,  // 17: proto.energyMeterApi.v1.EnergyMetersServices.RecentInstallationEnergyMeter:output_type -> proto.energyMeterApi.v1.ResponseEnergyMeter
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_v1_services_rest_api_energyMeter_proto_init() }
func file_internal_v1_services_rest_api_energyMeter_proto_init() {
	if File_internal_v1_services_rest_api_energyMeter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEnergyMeter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEnergyMeter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetEnergyMeters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUpdateEnergyMeters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_v1_services_rest_api_energyMeter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEnergyMeters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_v1_services_rest_api_energyMeter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_v1_services_rest_api_energyMeter_proto_goTypes,
		DependencyIndexes: file_internal_v1_services_rest_api_energyMeter_proto_depIdxs,
		MessageInfos:      file_internal_v1_services_rest_api_energyMeter_proto_msgTypes,
	}.Build()
	File_internal_v1_services_rest_api_energyMeter_proto = out.File
	file_internal_v1_services_rest_api_energyMeter_proto_rawDesc = nil
	file_internal_v1_services_rest_api_energyMeter_proto_goTypes = nil
	file_internal_v1_services_rest_api_energyMeter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EnergyMetersServicesClient is the client API for EnergyMetersServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnergyMetersServicesClient interface {
	GetEnergyMeters(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseGetEnergyMeters, error)
	CreateEnergyMeters(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseEnergyMeter, error)
	UpdateEnergyMeters(ctx context.Context, in *RequestUpdateEnergyMeters, opts ...grpc.CallOption) (*energyMeter.BoolResponse, error)
	DeleteEnergyMeters(ctx context.Context, in *energyMeter.IdRequest, opts ...grpc.CallOption) (*energyMeter.BoolResponse, error)
	InstalledCutOrInactiveEnergyMeter(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseGetEnergyMeters, error)
	RecentInstallationEnergyMeter(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseEnergyMeter, error)
}

type energyMetersServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewEnergyMetersServicesClient(cc grpc.ClientConnInterface) EnergyMetersServicesClient {
	return &energyMetersServicesClient{cc}
}

func (c *energyMetersServicesClient) GetEnergyMeters(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseGetEnergyMeters, error) {
	out := new(ResponseGetEnergyMeters)
	err := c.cc.Invoke(ctx, "/proto.energyMeterApi.v1.EnergyMetersServices/GetEnergyMeters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *energyMetersServicesClient) CreateEnergyMeters(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseEnergyMeter, error) {
	out := new(ResponseEnergyMeter)
	err := c.cc.Invoke(ctx, "/proto.energyMeterApi.v1.EnergyMetersServices/CreateEnergyMeters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *energyMetersServicesClient) UpdateEnergyMeters(ctx context.Context, in *RequestUpdateEnergyMeters, opts ...grpc.CallOption) (*energyMeter.BoolResponse, error) {
	out := new(energyMeter.BoolResponse)
	err := c.cc.Invoke(ctx, "/proto.energyMeterApi.v1.EnergyMetersServices/UpdateEnergyMeters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *energyMetersServicesClient) DeleteEnergyMeters(ctx context.Context, in *energyMeter.IdRequest, opts ...grpc.CallOption) (*energyMeter.BoolResponse, error) {
	out := new(energyMeter.BoolResponse)
	err := c.cc.Invoke(ctx, "/proto.energyMeterApi.v1.EnergyMetersServices/DeleteEnergyMeters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *energyMetersServicesClient) InstalledCutOrInactiveEnergyMeter(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseGetEnergyMeters, error) {
	out := new(ResponseGetEnergyMeters)
	err := c.cc.Invoke(ctx, "/proto.energyMeterApi.v1.EnergyMetersServices/InstalledCutOrInactiveEnergyMeter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *energyMetersServicesClient) RecentInstallationEnergyMeter(ctx context.Context, in *RequestEnergyMeter, opts ...grpc.CallOption) (*ResponseEnergyMeter, error) {
	out := new(ResponseEnergyMeter)
	err := c.cc.Invoke(ctx, "/proto.energyMeterApi.v1.EnergyMetersServices/RecentInstallationEnergyMeter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnergyMetersServicesServer is the server API for EnergyMetersServices service.
type EnergyMetersServicesServer interface {
	GetEnergyMeters(context.Context, *RequestEnergyMeter) (*ResponseGetEnergyMeters, error)
	CreateEnergyMeters(context.Context, *RequestEnergyMeter) (*ResponseEnergyMeter, error)
	UpdateEnergyMeters(context.Context, *RequestUpdateEnergyMeters) (*energyMeter.BoolResponse, error)
	DeleteEnergyMeters(context.Context, *energyMeter.IdRequest) (*energyMeter.BoolResponse, error)
	InstalledCutOrInactiveEnergyMeter(context.Context, *RequestEnergyMeter) (*ResponseGetEnergyMeters, error)
	RecentInstallationEnergyMeter(context.Context, *RequestEnergyMeter) (*ResponseEnergyMeter, error)
}

// UnimplementedEnergyMetersServicesServer can be embedded to have forward compatible implementations.
type UnimplementedEnergyMetersServicesServer struct {
}

func (*UnimplementedEnergyMetersServicesServer) GetEnergyMeters(context.Context, *RequestEnergyMeter) (*ResponseGetEnergyMeters, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnergyMeters not implemented")
}
func (*UnimplementedEnergyMetersServicesServer) CreateEnergyMeters(context.Context, *RequestEnergyMeter) (*ResponseEnergyMeter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnergyMeters not implemented")
}
func (*UnimplementedEnergyMetersServicesServer) UpdateEnergyMeters(context.Context, *RequestUpdateEnergyMeters) (*energyMeter.BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnergyMeters not implemented")
}
func (*UnimplementedEnergyMetersServicesServer) DeleteEnergyMeters(context.Context, *energyMeter.IdRequest) (*energyMeter.BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEnergyMeters not implemented")
}
func (*UnimplementedEnergyMetersServicesServer) InstalledCutOrInactiveEnergyMeter(context.Context, *RequestEnergyMeter) (*ResponseGetEnergyMeters, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstalledCutOrInactiveEnergyMeter not implemented")
}
func (*UnimplementedEnergyMetersServicesServer) RecentInstallationEnergyMeter(context.Context, *RequestEnergyMeter) (*ResponseEnergyMeter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecentInstallationEnergyMeter not implemented")
}

func RegisterEnergyMetersServicesServer(s *grpc.Server, srv EnergyMetersServicesServer) {
	s.RegisterService(&_EnergyMetersServices_serviceDesc, srv)
}

func _EnergyMetersServices_GetEnergyMeters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEnergyMeter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnergyMetersServicesServer).GetEnergyMeters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.energyMeterApi.v1.EnergyMetersServices/GetEnergyMeters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnergyMetersServicesServer).GetEnergyMeters(ctx, req.(*RequestEnergyMeter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnergyMetersServices_CreateEnergyMeters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEnergyMeter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnergyMetersServicesServer).CreateEnergyMeters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.energyMeterApi.v1.EnergyMetersServices/CreateEnergyMeters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnergyMetersServicesServer).CreateEnergyMeters(ctx, req.(*RequestEnergyMeter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnergyMetersServices_UpdateEnergyMeters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUpdateEnergyMeters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnergyMetersServicesServer).UpdateEnergyMeters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.energyMeterApi.v1.EnergyMetersServices/UpdateEnergyMeters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnergyMetersServicesServer).UpdateEnergyMeters(ctx, req.(*RequestUpdateEnergyMeters))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnergyMetersServices_DeleteEnergyMeters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(energyMeter.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnergyMetersServicesServer).DeleteEnergyMeters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.energyMeterApi.v1.EnergyMetersServices/DeleteEnergyMeters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnergyMetersServicesServer).DeleteEnergyMeters(ctx, req.(*energyMeter.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnergyMetersServices_InstalledCutOrInactiveEnergyMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEnergyMeter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnergyMetersServicesServer).InstalledCutOrInactiveEnergyMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.energyMeterApi.v1.EnergyMetersServices/InstalledCutOrInactiveEnergyMeter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnergyMetersServicesServer).InstalledCutOrInactiveEnergyMeter(ctx, req.(*RequestEnergyMeter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnergyMetersServices_RecentInstallationEnergyMeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEnergyMeter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnergyMetersServicesServer).RecentInstallationEnergyMeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.energyMeterApi.v1.EnergyMetersServices/RecentInstallationEnergyMeter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnergyMetersServicesServer).RecentInstallationEnergyMeter(ctx, req.(*RequestEnergyMeter))
	}
	return interceptor(ctx, in, info, handler)
}

var _EnergyMetersServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.energyMeterApi.v1.EnergyMetersServices",
	HandlerType: (*EnergyMetersServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnergyMeters",
			Handler:    _EnergyMetersServices_GetEnergyMeters_Handler,
		},
		{
			MethodName: "CreateEnergyMeters",
			Handler:    _EnergyMetersServices_CreateEnergyMeters_Handler,
		},
		{
			MethodName: "UpdateEnergyMeters",
			Handler:    _EnergyMetersServices_UpdateEnergyMeters_Handler,
		},
		{
			MethodName: "DeleteEnergyMeters",
			Handler:    _EnergyMetersServices_DeleteEnergyMeters_Handler,
		},
		{
			MethodName: "InstalledCutOrInactiveEnergyMeter",
			Handler:    _EnergyMetersServices_InstalledCutOrInactiveEnergyMeter_Handler,
		},
		{
			MethodName: "RecentInstallationEnergyMeter",
			Handler:    _EnergyMetersServices_RecentInstallationEnergyMeter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/v1/services/rest_api/energyMeter.proto",
}
