// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: internal/v1/energyMeter/energyMeter.proto

// Protobuf imports

// Local Imports

package energyMeterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnergyMeters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"id" json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: bson:"id" json:"id"
	Brand string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	// @inject_tag: bson:"address" json:"address"
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// @inject_tag: bson:"installation_date" json:"installation_date"
	InstallationDate string `protobuf:"bytes,4,opt,name=installation_date,json=installationDate,proto3" json:"installation_date,omitempty"`
	// @inject_tag: bson:"retirement_date" json:"retirement_date"
	RetirementDate string `protobuf:"bytes,5,opt,name=retirement_date,json=retirementDate,proto3" json:"retirement_date,omitempty"`
	// @inject_tag: bson:"serial" json:"serial"
	Serial string `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	// @inject_tag: bson:"lines" json:"lines"
	Lines int32 `protobuf:"varint,7,opt,name=lines,proto3" json:"lines,omitempty"`
	// @inject_tag: bson:"is_active" json:"is_active"
	IsActive bool `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// @inject_tag: bson:"created_at" json:"created_at"
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *EnergyMeters) Reset() {
	*x = EnergyMeters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_energyMeter_energyMeter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnergyMeters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyMeters) ProtoMessage() {}

func (x *EnergyMeters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_energyMeter_energyMeter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyMeters.ProtoReflect.Descriptor instead.
func (*EnergyMeters) Descriptor() ([]byte, []int) {
	return file_internal_v1_energyMeter_energyMeter_proto_rawDescGZIP(), []int{0}
}

func (x *EnergyMeters) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnergyMeters) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *EnergyMeters) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EnergyMeters) GetInstallationDate() string {
	if x != nil {
		return x.InstallationDate
	}
	return ""
}

func (x *EnergyMeters) GetRetirementDate() string {
	if x != nil {
		return x.RetirementDate
	}
	return ""
}

func (x *EnergyMeters) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *EnergyMeters) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *EnergyMeters) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EnergyMeters) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"id" json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_energyMeter_energyMeter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_energyMeter_energyMeter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_internal_v1_energyMeter_energyMeter_proto_rawDescGZIP(), []int{1}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response bool `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_v1_energyMeter_energyMeter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v1_energyMeter_energyMeter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_internal_v1_energyMeter_energyMeter_proto_rawDescGZIP(), []int{2}
}

func (x *BoolResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

var File_internal_v1_energyMeter_energyMeter_proto protoreflect.FileDescriptor

var file_internal_v1_energyMeter_energyMeter_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x22, 0x8e, 0x02, 0x0a, 0x0c, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x27, 0x0a, 0x0f, 0x72, 0x65, 0x74, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x74, 0x69, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x1b, 0x0a, 0x09, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2a, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x5a, 0x5a, 0x58, 0x68,
	0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x76, 0x69, 0x63, 0x74, 0x6f, 0x72, 0x63, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x65, 0x6e, 0x65, 0x72, 0x74, 0x62, 0x69, 0x74, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x3b, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x4d, 0x65, 0x74, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_v1_energyMeter_energyMeter_proto_rawDescOnce sync.Once
	file_internal_v1_energyMeter_energyMeter_proto_rawDescData = file_internal_v1_energyMeter_energyMeter_proto_rawDesc
)

func file_internal_v1_energyMeter_energyMeter_proto_rawDescGZIP() []byte {
	file_internal_v1_energyMeter_energyMeter_proto_rawDescOnce.Do(func() {
		file_internal_v1_energyMeter_energyMeter_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_v1_energyMeter_energyMeter_proto_rawDescData)
	})
	return file_internal_v1_energyMeter_energyMeter_proto_rawDescData
}

var file_internal_v1_energyMeter_energyMeter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_v1_energyMeter_energyMeter_proto_goTypes = []interface{}{
	(*EnergyMeters)(nil), // 0: proto.energyMeter.v1.EnergyMeters
	(*IdRequest)(nil),    // 1: proto.energyMeter.v1.IdRequest
	(*BoolResponse)(nil), // 2: proto.energyMeter.v1.BoolResponse
}
var file_internal_v1_energyMeter_energyMeter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_v1_energyMeter_energyMeter_proto_init() }
func file_internal_v1_energyMeter_energyMeter_proto_init() {
	if File_internal_v1_energyMeter_energyMeter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_v1_energyMeter_energyMeter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnergyMeters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_v1_energyMeter_energyMeter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_v1_energyMeter_energyMeter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_v1_energyMeter_energyMeter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_v1_energyMeter_energyMeter_proto_goTypes,
		DependencyIndexes: file_internal_v1_energyMeter_energyMeter_proto_depIdxs,
		MessageInfos:      file_internal_v1_energyMeter_energyMeter_proto_msgTypes,
	}.Build()
	File_internal_v1_energyMeter_energyMeter_proto = out.File
	file_internal_v1_energyMeter_energyMeter_proto_rawDesc = nil
	file_internal_v1_energyMeter_energyMeter_proto_goTypes = nil
	file_internal_v1_energyMeter_energyMeter_proto_depIdxs = nil
}
